---
engines:
  csslint:
    enabled: true
    checks:
      fallback-colors:
        enabled: false
      qualified-headings:
        enabled: false
      important:
        enabled: false
      universal-selector:
        enabled: false
      compatible-vendor-prefixes:
        enabled: false
      box-sizing:
        enabled: false
      star-property-hack:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "Wordpress"
    checks:
      WordPress NamingConventions ValidHookName UseUnderscores:
        enabled: false
      WordPress WP AlternativeFunctions file_system_read_file_get_contents:
        enabled: false
      Squiz PHP CommentedOutCode Found:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Naming/LongVariable:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- assets/vendor/*
- controls/js/dist/*
- controls/css/*
- lib/class-aricolor.php
- core/deprecated.php
- modules/webfonts/webfonts.php
- tests/*
- bin/*
- lib/*
