<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitafc2fa143fa2e272dcdbf5c3572fe9ad
{
    public static $files = array (
        'f80535149d9c08fd75226c2b6e8b42c3' => __DIR__ . '/..' . '/kirki-framework/control-base/src/aliases.php',
        '87c34c6c6680f5cbf57e2065b44cdcd1' => __DIR__ . '/..' . '/kirki-framework/core/src/aliases.php',
        '28bceabd95641c2ffed7c4a6c4140d56' => __DIR__ . '/..' . '/kirki-framework/control-color/src/aliases.php',
        '96da1597043dfa68372e8aeb47b5d7e3' => __DIR__ . '/..' . '/kirki-framework/control-background/src/aliases.php',
        '3828a3428ac6126936fc1807c796fd29' => __DIR__ . '/..' . '/kirki-framework/control-checkbox/src/aliases.php',
        'cb5bace3763fc0771eefd25ddf042dfe' => __DIR__ . '/..' . '/kirki-framework/control-code/src/aliases.php',
        '02e6283a844c2ddf6af174adc878ef5f' => __DIR__ . '/..' . '/kirki-framework/control-color-palette/src/aliases.php',
        '48169c443670736d2b1a514d020b64a1' => __DIR__ . '/..' . '/kirki-framework/control-cropped-image/src/aliases.php',
        '0bd495d9ba08e95186c90548d7cd511f' => __DIR__ . '/..' . '/kirki-framework/control-custom/src/aliases.php',
        '28e3cee4a082bd8768f3e773889743ca' => __DIR__ . '/..' . '/kirki-framework/control-dashicons/src/aliases.php',
        'c81bf14be6aed8a54dd795431d8f1609' => __DIR__ . '/..' . '/kirki-framework/control-date/src/aliases.php',
        '8de1edff898b5676084c9da7ee1847ef' => __DIR__ . '/..' . '/kirki-framework/control-dimension/src/aliases.php',
        'cf84c47a0ece0f40aa57c14236e7982e' => __DIR__ . '/..' . '/kirki-framework/control-dimensions/src/aliases.php',
        'bbfb95d513c9b499ebb3ff8793dfc7ce' => __DIR__ . '/..' . '/kirki-framework/module-css/src/aliases.php',
        '3c2e0be98245672dad9b32c8768ee4fd' => __DIR__ . '/..' . '/kirki-framework/module-css-vars/src/aliases.php',
        '4becfd0b1c4f3bd1c4b12db74525d49e' => __DIR__ . '/..' . '/kirki-framework/module-webfonts/src/aliases.php',
    );

    public static $prefixLengthsPsr4 = array (
        'K' => 
        array (
            'Kirki\\Modules\\Webfonts\\' => 23,
            'Kirki\\Modules\\CSS_Vars\\' => 23,
            'Kirki\\Modules\\CSS\\' => 18,
            'Kirki\\Core\\' => 11,
            'Kirki\\Control\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Kirki\\Modules\\Webfonts\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/module-webfonts/src',
        ),
        'Kirki\\Modules\\CSS_Vars\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/module-css-vars/src',
        ),
        'Kirki\\Modules\\CSS\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/module-css/src',
        ),
        'Kirki\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/core/src',
        ),
        'Kirki\\Control\\' => 
        array (
            0 => __DIR__ . '/..' . '/kirki-framework/control-background/src',
            1 => __DIR__ . '/..' . '/kirki-framework/control-base/src',
            2 => __DIR__ . '/..' . '/kirki-framework/control-checkbox/src',
            3 => __DIR__ . '/..' . '/kirki-framework/control-code/src',
            4 => __DIR__ . '/..' . '/kirki-framework/control-color/src',
            5 => __DIR__ . '/..' . '/kirki-framework/control-color-palette/src',
            6 => __DIR__ . '/..' . '/kirki-framework/control-cropped-image/src',
            7 => __DIR__ . '/..' . '/kirki-framework/control-custom/src',
            8 => __DIR__ . '/..' . '/kirki-framework/control-dashicons/src',
            9 => __DIR__ . '/..' . '/kirki-framework/control-date/src',
            10 => __DIR__ . '/..' . '/kirki-framework/control-dimension/src',
            11 => __DIR__ . '/..' . '/kirki-framework/control-dimensions/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitafc2fa143fa2e272dcdbf5c3572fe9ad::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitafc2fa143fa2e272dcdbf5c3572fe9ad::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
