<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'f80535149d9c08fd75226c2b6e8b42c3' => $vendorDir . '/kirki-framework/control-base/src/aliases.php',
    '87c34c6c6680f5cbf57e2065b44cdcd1' => $vendorDir . '/kirki-framework/core/src/aliases.php',
    '28bceabd95641c2ffed7c4a6c4140d56' => $vendorDir . '/kirki-framework/control-color/src/aliases.php',
    '96da1597043dfa68372e8aeb47b5d7e3' => $vendorDir . '/kirki-framework/control-background/src/aliases.php',
    '3828a3428ac6126936fc1807c796fd29' => $vendorDir . '/kirki-framework/control-checkbox/src/aliases.php',
    'cb5bace3763fc0771eefd25ddf042dfe' => $vendorDir . '/kirki-framework/control-code/src/aliases.php',
    '02e6283a844c2ddf6af174adc878ef5f' => $vendorDir . '/kirki-framework/control-color-palette/src/aliases.php',
    '48169c443670736d2b1a514d020b64a1' => $vendorDir . '/kirki-framework/control-cropped-image/src/aliases.php',
    '0bd495d9ba08e95186c90548d7cd511f' => $vendorDir . '/kirki-framework/control-custom/src/aliases.php',
    '28e3cee4a082bd8768f3e773889743ca' => $vendorDir . '/kirki-framework/control-dashicons/src/aliases.php',
    'c81bf14be6aed8a54dd795431d8f1609' => $vendorDir . '/kirki-framework/control-date/src/aliases.php',
    'bbfb95d513c9b499ebb3ff8793dfc7ce' => $vendorDir . '/kirki-framework/module-css/src/aliases.php',
    '3c2e0be98245672dad9b32c8768ee4fd' => $vendorDir . '/kirki-framework/module-css-vars/src/aliases.php',
    '4becfd0b1c4f3bd1c4b12db74525d49e' => $vendorDir . '/kirki-framework/module-webfonts/src/aliases.php',
);
