<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '87c34c6c6680f5cbf57e2065b44cdcd1' => $vendorDir . '/kirki-framework/core/src/aliases.php',
    'f80535149d9c08fd75226c2b6e8b42c3' => $vendorDir . '/kirki-framework/control-base/src/aliases.php',
    'bbfb95d513c9b499ebb3ff8793dfc7ce' => $vendorDir . '/kirki-framework/module-css/src/aliases.php',
    '3c2e0be98245672dad9b32c8768ee4fd' => $vendorDir . '/kirki-framework/module-css-vars/src/aliases.php',
);
