<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Kirki\\Settings\\' => array($vendorDir . '/kirki-framework/control-repeater/src/Settings'),
    'Kirki\\Modules\\Webfonts\\' => array($vendorDir . '/kirki-framework/module-webfonts/src'),
    'Kirki\\Modules\\Webfont_Loader\\' => array($vendorDir . '/kirki-framework/module-webfont-loader/src'),
    'Kirki\\Modules\\Tooltips\\' => array($vendorDir . '/kirki-framework/module-tooltips/src'),
    'Kirki\\Modules\\Selective_Refresh\\' => array($vendorDir . '/kirki-framework/module-selective-refresh/src'),
    'Kirki\\Modules\\Section_Icons\\' => array($vendorDir . '/kirki-framework/module-section-icons/src'),
    'Kirki\\Modules\\Preset\\' => array($vendorDir . '/kirki-framework/module-preset/src'),
    'Kirki\\Modules\\Postmessage\\' => array($vendorDir . '/kirki-framework/module-postmessage/src'),
    'Kirki\\Modules\\Loading\\' => array($vendorDir . '/kirki-framework/module-loading/src'),
    'Kirki\\Modules\\Field_Dependencies\\' => array($vendorDir . '/kirki-framework/module-field-dependencies/src'),
    'Kirki\\Modules\\Editor_Styles\\' => array($vendorDir . '/kirki-framework/module-editor-styles/src'),
    'Kirki\\Modules\\Custom_Sections\\' => array($vendorDir . '/kirki-framework/module-custom-sections/src'),
    'Kirki\\Modules\\Custom_Panels\\' => array($vendorDir . '/kirki-framework/module-custom-sections/src'),
    'Kirki\\Modules\\CSS_Vars\\' => array($vendorDir . '/kirki-framework/module-css-vars/src'),
    'Kirki\\Modules\\CSS\\' => array($vendorDir . '/kirki-framework/module-css/src'),
    'Kirki\\Field\\' => array($vendorDir . '/kirki-framework/control-background/src/Field', $vendorDir . '/kirki-framework/control-checkbox/src/Field', $vendorDir . '/kirki-framework/control-code/src/Field', $vendorDir . '/kirki-framework/control-color/src/Field', $vendorDir . '/kirki-framework/control-color-palette/src/Field', $vendorDir . '/kirki-framework/control-custom/src/Field', $vendorDir . '/kirki-framework/control-dashicons/src/Field', $vendorDir . '/kirki-framework/control-date/src/Field', $vendorDir . '/kirki-framework/control-dimension/src/Field', $vendorDir . '/kirki-framework/control-dimensions/src/Field', $vendorDir . '/kirki-framework/control-editor/src/Field', $vendorDir . '/kirki-framework/control-fontawesome/src/Field', $vendorDir . '/kirki-framework/control-generic/src/Field', $vendorDir . '/kirki-framework/control-image/src/Field', $vendorDir . '/kirki-framework/control-multicheck/src/Field', $vendorDir . '/kirki-framework/control-multicolor/src/Field', $vendorDir . '/kirki-framework/control-palette/src/Field', $vendorDir . '/kirki-framework/control-radio/src/Field', $vendorDir . '/kirki-framework/control-repeater/src/Field', $vendorDir . '/kirki-framework/control-select/src/Field', $vendorDir . '/kirki-framework/control-slider/src/Field', $vendorDir . '/kirki-framework/control-sortable/src/Field', $vendorDir . '/kirki-framework/control-upload/src/Field', $vendorDir . '/kirki-framework/field-typography/src/Field'),
    'Kirki\\Core\\' => array($vendorDir . '/kirki-framework/control-color-palette/src/Core', $vendorDir . '/kirki-framework/control-dashicons/src/Core', $vendorDir . '/kirki-framework/core/src'),
    'Kirki\\Control\\' => array($vendorDir . '/kirki-framework/control-background/src/Control', $vendorDir . '/kirki-framework/control-base/src/Control', $vendorDir . '/kirki-framework/control-checkbox/src/Control', $vendorDir . '/kirki-framework/control-code/src/Control', $vendorDir . '/kirki-framework/control-color/src/Control', $vendorDir . '/kirki-framework/control-color-palette/src/Control', $vendorDir . '/kirki-framework/control-cropped-image/src', $vendorDir . '/kirki-framework/control-custom/src/Control', $vendorDir . '/kirki-framework/control-dashicons/src/Control', $vendorDir . '/kirki-framework/control-date/src/Control', $vendorDir . '/kirki-framework/control-dimension/src/Control', $vendorDir . '/kirki-framework/control-dimensions/src/Control', $vendorDir . '/kirki-framework/control-editor/src/Control', $vendorDir . '/kirki-framework/control-fontawesome/src/Control', $vendorDir . '/kirki-framework/control-generic/src/Control', $vendorDir . '/kirki-framework/control-image/src/Control', $vendorDir . '/kirki-framework/control-multicheck/src/Control', $vendorDir . '/kirki-framework/control-multicolor/src/Control', $vendorDir . '/kirki-framework/control-palette/src/Control', $vendorDir . '/kirki-framework/control-radio/src/Control', $vendorDir . '/kirki-framework/control-repeater/src/Control', $vendorDir . '/kirki-framework/control-select/src/Control', $vendorDir . '/kirki-framework/control-slider/src/Control', $vendorDir . '/kirki-framework/control-sortable/src/Control', $vendorDir . '/kirki-framework/control-upload/src/Control', $vendorDir . '/kirki-framework/field-typography/src/Control'),
    'Kirki\\' => array($vendorDir . '/kirki-framework/field/src', $vendorDir . '/kirki-framework/googlefonts/src', $vendorDir . '/kirki-framework/url-getter/src'),
);
