<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Kirki\\Modules\\CSS_Vars\\' => array($vendorDir . '/kirki-framework/module-css-vars/src'),
    'Kirki\\Modules\\CSS\\' => array($vendorDir . '/kirki-framework/module-css/src'),
    'Kirki\\Core\\' => array($vendorDir . '/kirki-framework/core/src'),
    'Kirki\\Control\\' => array($vendorDir . '/kirki-framework/control-background/src', $vendorDir . '/kirki-framework/control-base/src', $vendorDir . '/kirki-framework/control-checkbox/src', $vendorDir . '/kirki-framework/control-code/src', $vendorDir . '/kirki-framework/control-color/src', $vendorDir . '/kirki-framework/control-color-palette/src', $vendorDir . '/kirki-framework/control-cropped-image/src', $vendorDir . '/kirki-framework/control-custom/src'),
);
