<?php return array(
    'root' => array(
        'pretty_version' => 'dev-develop',
        'version' => 'dev-develop',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '29bdb188f1b8af8dbc4ce68bf3350432ebb8f2d4',
        'name' => 'aristath/kirki',
        'dev' => true,
    ),
    'versions' => array(
        'aristath/kirki' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '29bdb188f1b8af8dbc4ce68bf3350432ebb8f2d4',
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'reference' => 'a241e78aaeb09781f5f5b92ac01ffd13ab43e5e8',
            'dev_requirement' => true,
        ),
        'dealerdirect/phpcodesniffer-composer-installer' => array(
            'pretty_version' => 'v0.7.1',
            'version' => '0.7.1.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../dealerdirect/phpcodesniffer-composer-installer',
            'aliases' => array(),
            'reference' => 'fe390591e0241955f22eb9ba327d137e501c771c',
            'dev_requirement' => true,
        ),
        'kirki-framework/compatibility' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/compatibility',
            'aliases' => array(),
            'reference' => 'c1dfc2577bff91dc98ad4d359345936b3f2a044b',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-base' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-base',
            'aliases' => array(),
            'reference' => 'cf0d6e4f3aa5576e2a1c56d9f63caad2fa3df580',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-checkbox' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-checkbox',
            'aliases' => array(),
            'reference' => '0bf14a2136f0f55caba0fdc6b7e67a3150508c15',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-code' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-code',
            'aliases' => array(),
            'reference' => 'c1ff86254792e8d6d03cf5ef0c848a29a6d7f879',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-color' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-color',
            'aliases' => array(),
            'reference' => 'facd7f051f0ec6be498cbfff5aa6d3d698b68f18',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-color-palette' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-color-palette',
            'aliases' => array(),
            'reference' => 'b3373ce7a97c4d4d516daea3c2443ec587a25330',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-cropped-image' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-cropped-image',
            'aliases' => array(),
            'reference' => '368b8e49c3238100ce832d688fcb684e4d68e69b',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-custom' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-custom',
            'aliases' => array(),
            'reference' => '134a69a61fdbc95a7d6c081b324eba262db80729',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-dashicons' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-dashicons',
            'aliases' => array(),
            'reference' => '5dd8e3fa00c4bea817d8cfaf27af760180c53772',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-date' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-date',
            'aliases' => array(),
            'reference' => 'ef61d9b261a1a73ada7fa33c06a047a336e6aae1',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-dimension' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-dimension',
            'aliases' => array(),
            'reference' => '3e53137ccce54fb86d40eabdd07923eea2fd693f',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-editor' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-editor',
            'aliases' => array(),
            'reference' => '933fb34ec7bd6a162f437c164480337ddb7c1693',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-generic' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-generic',
            'aliases' => array(),
            'reference' => 'c84bf46575df2b635efe3bb3345bf923dfaaa58f',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-image' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-image',
            'aliases' => array(),
            'reference' => '355fb103d429160d7cf629722b0ee131d82c4ebc',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-multicheck' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-multicheck',
            'aliases' => array(),
            'reference' => '59f7a990af47d928f3c34c37c7ce2609bee16573',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-radio' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-radio',
            'aliases' => array(),
            'reference' => '300c4e4ed77a7403ec5b2e10ca7b0215d6b95998',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-react-colorful' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-react-colorful',
            'aliases' => array(),
            'reference' => '37663cc7a2d1b11c75702afcebcb99cbec944c51',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-react-select' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-react-select',
            'aliases' => array(),
            'reference' => 'e2d79bebd239041db027c6dbe4b6c9e1fb1084bb',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-repeater' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-repeater',
            'aliases' => array(),
            'reference' => 'a07a53461ae5632d3a66f6758beea3b579f97b15',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-select' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-select',
            'aliases' => array(),
            'reference' => '1f4abff6dc6549720624bc8a1d0930a61cf52a50',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-slider' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-slider',
            'aliases' => array(),
            'reference' => '39ec5f5fc043d7d98401d1d7e7f70a33c0c2a30c',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-sortable' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-sortable',
            'aliases' => array(),
            'reference' => '28b15cb3eb2661be84842b40272ac400118145dc',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-upload' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-upload',
            'aliases' => array(),
            'reference' => '93eb0ab618025e3c6649cad4ced86d976d05c35a',
            'dev_requirement' => false,
        ),
        'kirki-framework/data-option' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/data-option',
            'aliases' => array(),
            'reference' => 'ee8efd9a572c8df70e86d068058ad391800a754f',
            'dev_requirement' => false,
        ),
        'kirki-framework/field' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field',
            'aliases' => array(),
            'reference' => 'aa2acfe588c775328a268a4f092495df6b116773',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-background' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-background',
            'aliases' => array(),
            'reference' => 'd16f53564b0b5c0c2f94626098540e86d6aa8e50',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-dimensions' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-dimensions',
            'aliases' => array(),
            'reference' => '0f2411214894dcb993c2df0a22e2b8f175f99a5c',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-fontawesome' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-fontawesome',
            'aliases' => array(),
            'reference' => 'ddcdec292f5d302a39fdb86ca81ce326403bcc27',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-multicolor' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-multicolor',
            'aliases' => array(),
            'reference' => 'fb40978fc9617e6c9634eadcb0751d0c71f8cea6',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-typography' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-typography',
            'aliases' => array(),
            'reference' => 'd6d16ef3ffa9f6e2c6c29f3bd3a32be2007c5ebf',
            'dev_requirement' => false,
        ),
        'kirki-framework/googlefonts' => array(
            'pretty_version' => 'v19.09.22',
            'version' => '19.09.22.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/googlefonts',
            'aliases' => array(),
            'reference' => 'd943e605c1dfb985dbe2cd1bd94e005a6e5fe65b',
            'dev_requirement' => false,
        ),
        'kirki-framework/l10n' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/l10n',
            'aliases' => array(),
            'reference' => '6aa25316f3a11f6ec491389cdd7d6dee13edbef8',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-css' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-css',
            'aliases' => array(),
            'reference' => 'b2f10adcbfe98c384eedb5594f52fc7a7daa59e2',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-editor-styles' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-editor-styles',
            'aliases' => array(),
            'reference' => 'fde4dcc61727bd19c5a7e9dfcc9c079cf7ee3437',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-field-dependencies' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-field-dependencies',
            'aliases' => array(),
            'reference' => '31e1788fbe7bef910698a7362f9ce7bfc78bb304',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-panels' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-panels',
            'aliases' => array(),
            'reference' => '3e754b04b09ddb38c9e72d7d1d536372152eb0f5',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-postmessage' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-postmessage',
            'aliases' => array(),
            'reference' => 'fda89740079626acc35f6dd61b89b72b96a38f5b',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-preset' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-preset',
            'aliases' => array(),
            'reference' => 'c968bbeae70145409628d7ac624b8ffb6f378652',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-sections' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-sections',
            'aliases' => array(),
            'reference' => '7c042cae27476d539b33c8ce55f7469d3668a6bd',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-selective-refresh' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-selective-refresh',
            'aliases' => array(),
            'reference' => '1fe1326c09df7cda2e3b29bae878369c9ef82e11',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-tooltips' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-tooltips',
            'aliases' => array(),
            'reference' => 'becd264e50ec81314b6a3e373332629bd9e662ef',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-webfonts' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-webfonts',
            'aliases' => array(),
            'reference' => '5fc5a286105c37f9f78c6462b71369d0d2e8f590',
            'dev_requirement' => false,
        ),
        'kirki-framework/url-getter' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/url-getter',
            'aliases' => array(),
            'reference' => '2b1b464b4ba7d2a3d37094669dd66f20d39fa9e3',
            'dev_requirement' => false,
        ),
        'kirki-framework/util' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/util',
            'aliases' => array(),
            'reference' => '7ead5a4bf6875aa1afb96cbb4e747c59c163b2a3',
            'dev_requirement' => false,
        ),
        'phpcompatibility/php-compatibility' => array(
            'pretty_version' => '9.3.5',
            'version' => '9.3.5.0',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcompatibility/php-compatibility',
            'aliases' => array(),
            'reference' => '9fb324479acf6f39452e0655d2429cc0d3914243',
            'dev_requirement' => true,
        ),
        'phpcompatibility/phpcompatibility-paragonie' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcompatibility/phpcompatibility-paragonie',
            'aliases' => array(),
            'reference' => 'ddabec839cc003651f2ce695c938686d1086cf43',
            'dev_requirement' => true,
        ),
        'phpcompatibility/phpcompatibility-wp' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcompatibility/phpcompatibility-wp',
            'aliases' => array(),
            'reference' => 'a792ab623069f0ce971b2417edef8d9632e32f75',
            'dev_requirement' => true,
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.6.1',
            'version' => '3.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'reference' => 'f268ca40d54617c6e06757f83f699775c9b3ff2e',
            'dev_requirement' => true,
        ),
        'wp-coding-standards/wpcs' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../wp-coding-standards/wpcs',
            'aliases' => array(),
            'reference' => '7da1894633f168fe244afc6de00d141f27517b62',
            'dev_requirement' => true,
        ),
        'wptrt/wpthemereview' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../wptrt/wpthemereview',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '15684d0852fe90d807c2ae7746dea1302b74b4bd',
            'dev_requirement' => true,
        ),
    ),
);
