<?php return array(
    'root' => array(
        'pretty_version' => 'dev-develop',
        'version' => 'dev-develop',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '1c74e651c264d22b167fd8d4106bd14e63b180f2',
        'name' => 'aristath/kirki',
        'dev' => true,
    ),
    'versions' => array(
        'aristath/kirki' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '1c74e651c264d22b167fd8d4106bd14e63b180f2',
            'dev_requirement' => false,
        ),
        'codacy/coverage' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codacy/coverage',
            'aliases' => array(),
            'reference' => '656913b35e22ae0d1ec352bc00e3ad90616efb7a',
            'dev_requirement' => true,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'reference' => '5a546a8cc4607f38cfbd8e20b3de234e45b2110f',
            'dev_requirement' => true,
        ),
        'dealerdirect/phpcodesniffer-composer-installer' => array(
            'pretty_version' => 'v0.7.1',
            'version' => '0.7.1.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../dealerdirect/phpcodesniffer-composer-installer',
            'aliases' => array(),
            'reference' => 'fe390591e0241955f22eb9ba327d137e501c771c',
            'dev_requirement' => true,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'reference' => 'd56bf6102915de5702778fe20f2de3b2fe570b5b',
            'dev_requirement' => true,
        ),
        'gitonomy/gitlib' => array(
            'pretty_version' => 'v1.2.3',
            'version' => '1.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gitonomy/gitlib',
            'aliases' => array(),
            'reference' => 'd22f212b97fdb631ac73dfae65c194dc4cb0d227',
            'dev_requirement' => true,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.3.0',
            'version' => '7.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '7008573787b430c1c1f650e3722d9bba59967628',
            'dev_requirement' => true,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => '8e7d04f1f6450fef59366c399cfad4b9383aa30d',
            'dev_requirement' => true,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => '1dc8d9cba3897165e16d12bb13d813afb1eb3fe7',
            'dev_requirement' => true,
        ),
        'kirki-framework/compatibility' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/compatibility',
            'aliases' => array(),
            'reference' => '08aeffcec4d3b3827a4f5176a277aa6f9866d23d',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-base' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-base',
            'aliases' => array(),
            'reference' => '6bcf8ed614608186ee51ba4612e11328173c6174',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-checkbox' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-checkbox',
            'aliases' => array(),
            'reference' => '9d1baf8cb576bd7ec97dd9493768893b86985eca',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-code' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-code',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'c1ff86254792e8d6d03cf5ef0c848a29a6d7f879',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-color' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-color',
            'aliases' => array(),
            'reference' => '50717cc7873658dc4fc97b06e7cbe134bc18d400',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-cropped-image' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-cropped-image',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '368b8e49c3238100ce832d688fcb684e4d68e69b',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-custom' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-custom',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '134a69a61fdbc95a7d6c081b324eba262db80729',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-dashicons' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-dashicons',
            'aliases' => array(),
            'reference' => '7b697fed3136a42d2efad21a80075cbea12d1e0f',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-date' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-date',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '8165687d106fa30b6fded9325dc716c657752948',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-dimension' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-dimension',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '0d73be1ae17d3cf73c454bec1b6ea60c4753ec4f',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-editor' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-editor',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'bd6175c75bb4c046f3d80711f6bccf3cbaab598f',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-generic' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-generic',
            'aliases' => array(),
            'reference' => '49678ddd3e3d26c7f5a174e59f22afcc69cf7408',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-image' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-image',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'be2c2324f88a04b7aaf9c6cd958b59eeb26dbb0e',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-multicheck' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-multicheck',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'd60de676b2ee0f58d537b954f24050f0ae3425ee',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-palette' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-palette',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '178413d19ab8311312e64cb248c02043955cc783',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-radio' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-radio',
            'aliases' => array(),
            'reference' => '74acf02e1fbc39167eeecaa1ab065b2c6fe4aa82',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-react-color' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-react-color',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '58c685251c90c94622a5550166ff18119f8c577c',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-react-colorful' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-react-colorful',
            'aliases' => array(),
            'reference' => 'f0c18ba16fd397edd4f994f8fa85b5230a208dda',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-react-select' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-react-select',
            'aliases' => array(),
            'reference' => '0a97b66e27e17bfb9b96b26484a258081fe847e1',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-repeater' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-repeater',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '85baf5842b2729b0eaee481150f5a1c19ef90c3a',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-select' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-select',
            'aliases' => array(),
            'reference' => '1f4abff6dc6549720624bc8a1d0930a61cf52a50',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-slider' => array(
            'pretty_version' => 'v0.2.4',
            'version' => '0.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-slider',
            'aliases' => array(),
            'reference' => '793bb27ff0255e39e8daacb18ee7282ef13efe7e',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-sortable' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-sortable',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '05d0fbdf4e5486888b6df0b0a21677c2b7546f06',
            'dev_requirement' => false,
        ),
        'kirki-framework/control-upload' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/control-upload',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'e1d5a0a12a31b0cd372d02db49d7cadd332720d3',
            'dev_requirement' => false,
        ),
        'kirki-framework/data-option' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/data-option',
            'aliases' => array(),
            'reference' => 'ee8efd9a572c8df70e86d068058ad391800a754f',
            'dev_requirement' => false,
        ),
        'kirki-framework/field' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '5865773dd95b4d75c9534be2d58dde4251a06626',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-background' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-background',
            'aliases' => array(),
            'reference' => '5067b48202055eba181a7b71a1f30ab809f6aa45',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-color-palette' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-color-palette',
            'aliases' => array(),
            'reference' => '3809ca2fa7d6c3f98add779891ad963c0785f0d0',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-dimensions' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-dimensions',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '385e2d12dcab85cdec192c8ee6848863c26ac5c9',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-fontawesome' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-fontawesome',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'ddcdec292f5d302a39fdb86ca81ce326403bcc27',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-multicolor' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-multicolor',
            'aliases' => array(),
            'reference' => 'c33fbce81df6662c5fd81fbf680008afbee347f7',
            'dev_requirement' => false,
        ),
        'kirki-framework/field-typography' => array(
            'pretty_version' => 'v0.3.1',
            'version' => '0.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/field-typography',
            'aliases' => array(),
            'reference' => '2c060f5b6298a06ef863601f9075d094e7bcd098',
            'dev_requirement' => false,
        ),
        'kirki-framework/googlefonts' => array(
            'pretty_version' => 'v19.09.22',
            'version' => '19.09.22.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/googlefonts',
            'aliases' => array(),
            'reference' => 'd943e605c1dfb985dbe2cd1bd94e005a6e5fe65b',
            'dev_requirement' => false,
        ),
        'kirki-framework/l10n' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/l10n',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '6aa25316f3a11f6ec491389cdd7d6dee13edbef8',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-css' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-css',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'cf068a37d950f54f3275bf7b13e1be2437501f78',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-editor-styles' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-editor-styles',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '9c2b629b832a0ba8eead9cb6a177205f894b943b',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-field-dependencies' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-field-dependencies',
            'aliases' => array(),
            'reference' => '9882cbfdde73192ff4b3fcf3ad1d994cdf339f27',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-panels' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-panels',
            'aliases' => array(),
            'reference' => '3e754b04b09ddb38c9e72d7d1d536372152eb0f5',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-postmessage' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-postmessage',
            'aliases' => array(),
            'reference' => '15697b26ce05df057a23da6c4faaec57b4ee6fa5',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-preset' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-preset',
            'aliases' => array(),
            'reference' => 'c968bbeae70145409628d7ac624b8ffb6f378652',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-sections' => array(
            'pretty_version' => 'dev-nightly',
            'version' => 'dev-nightly',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-sections',
            'aliases' => array(),
            'reference' => '7c042cae27476d539b33c8ce55f7469d3668a6bd',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-selective-refresh' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-selective-refresh',
            'aliases' => array(),
            'reference' => '826dad18131bd4d6e9fdd4dde2eaa2f338801692',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-tooltips' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-tooltips',
            'aliases' => array(),
            'reference' => '9fc1430896b0bc0f2cddc402e36ac2d8725ad1e5',
            'dev_requirement' => false,
        ),
        'kirki-framework/module-webfonts' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/module-webfonts',
            'aliases' => array(),
            'reference' => '5fc5a286105c37f9f78c6462b71369d0d2e8f590',
            'dev_requirement' => false,
        ),
        'kirki-framework/url-getter' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/url-getter',
            'aliases' => array(),
            'reference' => '2b1b464b4ba7d2a3d37094669dd66f20d39fa9e3',
            'dev_requirement' => false,
        ),
        'kirki-framework/util' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kirki-framework/util',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => 'b572a335388d9d2f603f8dca717f0e224f0700a9',
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.10.2',
            'version' => '1.10.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'reference' => '776f831124e9c62e1a2c601ecc52e776d8bb7220',
            'dev_requirement' => true,
            'replaced' => array(
                0 => '1.10.2',
            ),
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.12.0',
            'version' => '4.12.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '6608f01670c3cc5079e18c1dab1104e002579143',
            'dev_requirement' => true,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'reference' => '97803eca37d319dfa7826cc2437fc020857acb53',
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'reference' => 'bae7c545bef187884426f042434e561ab1ddb182',
            'dev_requirement' => true,
        ),
        'php-coveralls/php-coveralls' => array(
            'pretty_version' => 'v2.4.3',
            'version' => '2.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-coveralls/php-coveralls',
            'aliases' => array(),
            'reference' => '909381bd40a17ae6e9076051f0d73293c1c091af',
            'dev_requirement' => true,
        ),
        'phpcompatibility/php-compatibility' => array(
            'pretty_version' => '9.3.5',
            'version' => '9.3.5.0',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcompatibility/php-compatibility',
            'aliases' => array(),
            'reference' => '9fb324479acf6f39452e0655d2429cc0d3914243',
            'dev_requirement' => true,
        ),
        'phpcompatibility/phpcompatibility-paragonie' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcompatibility/phpcompatibility-paragonie',
            'aliases' => array(),
            'reference' => 'ddabec839cc003651f2ce695c938686d1086cf43',
            'dev_requirement' => true,
        ),
        'phpcompatibility/phpcompatibility-wp' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcompatibility/phpcompatibility-wp',
            'aliases' => array(),
            'reference' => 'a792ab623069f0ce971b2417edef8d9632e32f75',
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.2.2',
            'version' => '5.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'reference' => '069a785b2141f5bcf49f3e353548dc1cce6df556',
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'reference' => '6a467b8989322d92aa1c8bf2bebcc6e5c2ba55c0',
            'dev_requirement' => true,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'reference' => 'be1996ed8adc35c3fd795488a653f4b518be70ea',
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.6',
            'version' => '9.2.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'reference' => 'f6293e1b30a2354e8428e004689671b83871edde',
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.5',
            'version' => '3.0.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'reference' => 'aa4be8575f26070b100fccb67faabb28f21f66f8',
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.5.9',
            'version' => '9.5.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'reference' => 'ea8c2dfb1065eb35a79b3681eee6e6fb0a6f273b',
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '8622567409010282b7aeebe4bb841fe98b58dcaf',
            'dev_requirement' => true,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'dev_requirement' => true,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'dev_requirement' => true,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => true,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => true,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => true,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'reference' => '442e7c7e687e42adc03470c7b668bc4b2402c0b2',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'reference' => '55f4261989e546dc112258c7a75935a81a7ce382',
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'reference' => '739b35e53379900cc9ac327b2147867b8b6efd88',
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'reference' => '3461e3fccc7cfdfc2720be910d3bd73c69be590d',
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.3',
            'version' => '5.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'reference' => '388b6ced16caa751030f6a69e588299fa09200ac',
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.3',
            'version' => '4.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'reference' => 'd89cc98761b8cb5a1a235a6b703ae50d34080e65',
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'reference' => '23bd5951f7ff26f12d4e3242864df3e08dec4e49',
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'reference' => 'c1c2e997aa3146983ed888ad08b15470a2e22ecc',
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'reference' => 'cd9d8cf3c5804de4341c283ed787f099f5506172',
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'reference' => '0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8',
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '2.3.4',
            'version' => '2.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'reference' => 'b8cd8a1c753c90bc1a0f5372170e3e489136f914',
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'dev_requirement' => true,
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.6.0',
            'version' => '3.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'reference' => 'ffced0d2c8fa8e6cdc4d695a743271fab6c38625',
            'dev_requirement' => true,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v5.3.4',
            'version' => '5.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'reference' => '4268f3059c904c61636275182707f81645517a37',
            'dev_requirement' => true,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.3.7',
            'version' => '5.3.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => '8b1008344647462ae6ec57559da166c2bfa5e16a',
            'dev_requirement' => true,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => '5f38c8804a9e97d23e0c8d63341088cd8a22d627',
            'dev_requirement' => true,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v5.3.4',
            'version' => '5.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'reference' => '343f4fe324383ca46792cae728a3b6e2f708fb32',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => '46cd95797e9df938fdd2b03693b5fca5e64b01ce',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'reference' => '16880ba9c5ebe3642d1995ab866db29270b36535',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '8590a5f561694770bdcd3f9b5c69dde6945028e8',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '9174a3d80210dca8daa7f31fec659150bbeabfc6',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => 'fba8933c384d6476ab14fb7b8526e5287ca7e010',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.23.1',
            'version' => '1.23.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '1100343ed1a92e3a38f9ae122fc0eb21602547be',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'reference' => 'e66119f3de95efc359483f810c4c3e6436279436',
            'dev_requirement' => true,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v5.3.7',
            'version' => '5.3.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => '38f26c7d6ed535217ea393e05634cb0b244a1967',
            'dev_requirement' => true,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'reference' => 'f040a30e04b57fbcc9c6cbcf4dbaa96bd318b9bb',
            'dev_requirement' => true,
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v5.3.4',
            'version' => '5.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'reference' => 'b24c6a92c6db316fee69e38c80591e080e41536c',
            'dev_requirement' => true,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v5.3.7',
            'version' => '5.3.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'reference' => '8d224396e28d30f81969f083a58763b8b9ceb0a5',
            'dev_requirement' => true,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.3.6',
            'version' => '5.3.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '4500fe63dc9c6ffc32d3b1cb0448c329f9c814b7',
            'dev_requirement' => true,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'dev_requirement' => true,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => '6964c76c7804814a842473e0c8fd15bab0f18e25',
            'dev_requirement' => true,
        ),
        'wp-coding-standards/wpcs' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../wp-coding-standards/wpcs',
            'aliases' => array(),
            'reference' => '7da1894633f168fe244afc6de00d141f27517b62',
            'dev_requirement' => true,
        ),
        'wptrt/wpthemereview' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../wptrt/wpthemereview',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '15684d0852fe90d807c2ae7746dea1302b74b4bd',
            'dev_requirement' => true,
        ),
    ),
);
